# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master,TSSA ]
  pull_request:
    branches: [ master,TSSA ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
  
    timeout-minutes: 30
    runs-on: self-hosted
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2    

      - name: Restart Master with new config
        run: sudo systemctl restart salt-master
        id: Restart_Salt_Master
      - name: Test Server salt-call
        run: sudo salt-call state.apply
        id: Run_Server_salt-call_statedotapply
      - name: Test Prometheus Config
        run: sudo promtool check config /etc/prometheus/prometheus.yml 
        id: Check_prom_config_after_salt-call
